apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ .Values.service.name }}.{{ .Values.ingress.env }}.{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.externalPort }}
